project:
  type: book
  output-dir : docs

book:
  title: "파인만 물리학 강의"
  author: "Julia-KAERI"
  date: "2/11/2024"
  page-navigation: true

  
  chapters:
    - index.qmd

    - part: src/00_index.qmd    
      chapters: 
      - src/vol1/vol1_1.qmd
      - src/vol1/vol1_2.qmd
      - src/vol1/vol1_3.qmd
      - src/vol1/vol1_4.qmd
      - src/vol2/vol2_1.qmd

    - part: src/exercises/index.qmd
      chapters:
      - src/exercises/exercises_1_1.qmd
      # - src/Feynmann/feynmann_trans.qmd
  
 
    - references.qmd

bibliography: references.bib

format:
  html:
    title-block-banner: true
    # include-in-header: 
    #   - html-hacks/load-font-awesome.html
    #   - html-hacks/load-xkcd-font.html
    # resources: web-resources/**
    # https://quarto.org/src/output-formats/html-themes.html#overview
    # theme: darkly
    theme: cosmo
    fontsize: 0.9em
    toc: true
    collapse: true
    # css: styles.css
    number-sections: true

    code-fold: true
    code-summary: "Show the code"
  
    html-math-method: mathjax




