---
title: "연습문제 1~"
number-sections: true
number-depth: 0
crossref:
  chapters: true
---


{{< include ../../latexmacros.qmd >}} 

## 1. Atoms in Motion {#sec-FLPEXR_1_1}

*파인만 물리학 강의 1 권 1장 ~ 3장에 해당한다.*


<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

**1.1** 열이 단지 분자의 운동이라면 뜨거운 멈춘 공과 차가운 빠른 공의 차이는 무엇인가?

</div>

::: {.solution}

공의 질량 중심은 멈춰 있지만 각 분자들은 빠르게 움직일 수 있으며, 공의 질량 중심은 빨리 움직이지만 공의 각 분자들은 천천히 움직일 수 있다.

:::



<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

**1.2** 모든 물체의 원자들이 끊임없이 움직인다면 화석 자국과 같은 영구적인 물체는 어떻게 가능한가?

</div>

::: {.solution}

:::

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

**1.3** 움직이는 기계의 마찰이 왜 그리고 어떻게 열을 만들어 내는지 정성적으로 설명하라. 또한 이 과정을 정반대로 했을 때 열이 유용한 움직임을 만들어 낼 수 없는지 정성적으로 설명해보라.

</div>

::: {.solution}

:::


<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

**1.4** 화학자들은 고무 분자들이 길고 서로 교차하는 원자들의 사슬로 이루어졌다는 것을 발견했다. 고무를 늘리면 고무줄의 온도가 올라가는 이유를 설명하라.

</div>

::: {.solution}

:::

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

**1.5** 무게를 지탱하고 있는 고무줄에 열을 가하면 무슨 일이 벌어질지 설명하라.

</div>

::: {.solution}

:::


<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

**1.6** 정 오각형 모양을 가진 결정이 없는 이유를 설명하라.

</div>

::: {.solution}

:::

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

**1.7** 지름이 $d$ 인 쇠공을 매우 많이 가지고 있다고 하자. 그리고 부피 $V$ 인 상자를 생각하자. 상자의 모든 치수는 $d$ 보다 매우 크다. 상자가 담을수 있는 가장 많은 공의 수는 얼마인가? 

</div>

::: {.solution}

:::


<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

**1.8** 기체의 압력 $P$ 는 기체 원자의 개수 밀도 $n$, 원자의 평균 속력 $\langle v\rangle$ 에 대해 어떻게 변하는가? ($P$ 는 $n$ 혹은 $\langle v\rangle$ 에 비례해야 하는가? 아니면 더 크게 혹은 더 작게 변해야 하는가?)

</div>

::: {.solution}
이상기체의 경우 $P= nk_B T$ 이고 $\langle v\rangle \propto T$ 임을 안다. 


:::


<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

**1.9** 일반적인 기체의 부피는 0.001 $\text{g/cm}^{3}$ 이며 액체 공기의 부피는 1.0 $\text{g/cm}^{3}$ 이다.

($a$) 일반적인 공기의 개수 밀도 $n_G$ 와 액체 공기의 개수 밀도 $n_L$ 을 구하라.

($b$) 공기 분자의 질량 $m$ 을 구하라.

($c$) 상온($20\,^\circ \text{C}$) 상압(1 atm) 에서 공기 분자가 충돌 사이에 진행하는 거리 $l$ 을 구하라. 이를 **평균 자유 거리(mean free path)** 라고 한다.

($d$) 보통의 대기에서 평균자유거리가 1 m 가 되기 위한 압력은 얼마인가?
</div>

::: {.solution}
$\,$($a$) 
 


:::
